# Практическое задание 2

Будем работать с датасетом Pima Indian Diabetes - это набор данных из Национального института диабета, болезней органов пищеварения и почек. Целью набора данных является диагностическое прогнозирование наличия диабета у пациента. Несколько ограничений были наложены на выбор этих экземпляров из большой базы данных. В частности, все пациенты здесь - женщины в возрасте от 21 года, индийского происхождения.

Описание данных:

- __Pregnancies__ - данная единица отображает количество беременностей, единицы измерения - целые числа от 0 до N. Тип переменной - количественная, дискретная.
- __Glucose__ - данная единица отображает уровень глюкозы в крови, единицы измерения - целые числа. Тип переменной - количественная, дискретная.
- __BloodPressure__ - данная единица отображает артериальное давление, единицы измерения - миллиметры р/с, целые числа. Тип переменной - количественная, дискретная.
- __SkinThickness__ - данная единица отображает обхват трицепса в миллиметрах, целые числа. Тип переменной - количественная, дискретная.
- __Insulin__ - данная единица отображает уровень инсулина в крови, целые числа. Тип переменной - количественная, дискретная.
- __BMI__ - данная единица отображает индекс массы тела. Тип переменной - количественная, непрерывная.
- __DiabetesPedigreeFunction__ - данная единица отображает риск наследственного диабета в зависимости наличия диабета у родственников. Выражается десятичной дробью от 0 до 1. Тип переменной - количественная, непрерывная.
- __Age__ - данная единица отражает возраст в целых числах. Тип переменной - количественная, дискретная.
- __Class__ - данная единица отражает наличие диабета у субъекта, выражена 0(здоров) или 1(болен). Тип переменной - категориальная, бинарная.

In [19]:
import pandas as pd

df = pd.read_csv("diabetes.csv")
df = df.loc[~df.duplicated()]
df.to_csv("filtred_diabetes.csv", sep = ',')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0

**Задание 1.**

У скольких женщин старше 50 лет обнаружен диабет?

In [ ]:
# Ваше решение здесь
# Для ответа на вопрос используйте метода print() и приемы форматирования строк 

ladys_diabetes = df.loc[(df['Age'] > 50) &
                        (df['Class'] == 1)].shape[0]

print(f"У {ladys_diabetes} женщин старше 50 лет обнаружен диабет.")

У 38 женщин старше 50 лет обнаружен диабет.

**Задание 2.**

Сколько женщин возраста между 30 и 40 успело родить 3 или более детей?

In [ ]:
# Ваше решение здесь

ladys_big_mom = df.loc[(df['Age'] >= 30) &
                       (df['Age'] <= 40) &
                       (df['Pregnancies'] >= 3)].shape[0]
                       
print((f"У {ladys_big_mom} женщин в возрасте от 30 до 40 лет трое или более детей."))

У 142 женщин в возрасте от 30 до 40 лет трое или более детей.

**Задание 3.**

Нормальным кровяным давлением будем считать давление в диапазоне [80-89]. У какого процента женщин давление нормальное?

In [ ]:
# Ваше решение здесь

ladys_pressure = df.loc[(df['BloodPressure'] >= 80) &
                        (df['BloodPressure'] <= 89)].shape[0]
                        
print((f"У {round(ladys_pressure/df.shape[0]*100, 2)} % женщин давление в норме."))

У 18.88 % женщин давление в норме.

**Задание 4.**

Сравните процент больных диабетом среди женщин, которые были беременны и не были.

In [46]:
# Ваше решение здесь

def check(a, b):
  return abs(a - b)

df_ladys_pregnant = df.loc[(df['Pregnancies'] > 0)]
df_ladys_no_pregnant = df.loc[(df['Pregnancies'] == 0)]

ladys_pregnant_d = df_ladys_pregnant.loc[(df['Class'] == 1)].shape[0]
ladys_no_pregnant_d = df_ladys_no_pregnant.loc[(df['Class'] == 1)].shape[0]

a = ladys_pregnant_d/df_ladys_pregnant.shape[0]
b = ladys_no_pregnant_d/df_ladys_no_pregnant.shape[0]

print("По статистике у женщин после родов процент диабета составляет: "
      f"{round(a * 100, 3)} %")
print("По статистике у женщин без детей процент диабета составляет: "
      f"{round(b * 100, 3)} %")
print("Разница составляет: "
      f"{round(check(a, b) * 100, 3)} %")

По статистике у женщин после родов процент диабета составляет: 35.008 %
По статистике у женщин без детей процент диабета составляет: 34.234 %
Разница составляет: 0.773 %