# Домашнее задание 5

Работа с базой `book_simple.db`. 

<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=160L6VoP2kz8mJfpFuLWF6_SdoVcvkT-J' width="400" height="400" />
<figcaption>Структура базы book </figcaption></center>
</figure>

Ознакомиться со структурой данных можно с ипользованием, например, программы DBeaмer. 

Для работы с базой допускается использовать только возможности SQL. 
Библиотеку Pandas допускается использовать только просмотра результата.

Шаг 1.  Изучите материалы лекционных и практических занятий по теме 6.1-6.4.

Шаг 2. Получите результирующие множества из БД в соответствии с следующими условиями выборки, сортировки, группировки данных:

1. Выведите авторов, имеющихся в базе?
2. Найдите всех авторов с инициалами "С. А.". Автор в базе определяется так: И. О. Фамилия
3. Найдите все издательства, название которых состоит из двух и более слов.
4. Выведите список книг, выпущенных в издательстве "Мир".
5. Выведите количество книг, принадлежащих каждой из категорий. Результат отсортировать по возрастанию.
6. Выведите количество книг, выпущенных в каждом издательстве. В итоговом списке оставьте только те издательства, которые выпустили 3 и более книг. Результат отсортировать по убыванию.
7. Выведите список книг, автором которых являлся <<С. А. Айвазян>>.
8. В каких издательствах и сколько выпускались книги за авторством <<С. А. Айвазян>>. Результат отсортировать по убыванию.

Шаг 3. Результат каждого запроса запишите в виде таблицы в БД book.db.

Шаг 4. Опубликуйте итоговый файл БД расширения sql, прикрепив его в этом задании.

In [197]:
# Подключение библиотек
import sqlite3
import pandas as pd

In [198]:
# Подключение к БД
con = sqlite3.connect('book_simple.db')
cur = con.cursor()

In [199]:
# Ваши запросы здесь
q_tables = """
SELECT 
    name
  FROM 
    sqlite_master;
"""
cur.execute(q_tables).fetchall()

[('author',),
 ('author_name',),
 ('publisher',),
 ('publisher_name',),
 ('category',),
 ('category_code',),
 ('category_title',),
 ('book',),
 ('book_publisher_id',),
 ('book_category_id',),
 ('authorbook',)]

Выведите авторов, имеющихся в базе

In [200]:
q_authors = """
SELECT 
    name
  FROM 
    author;
"""
pd.read_sql(q_authors, con)

                 name
0      М. А. Айзерман
1     Ф. Т. Алескеров
2      Г. В. Савицкая
3          В. Кельтон
4              А. Лоу
...               ...
1005   В. Н. Касьянов
1006        Ф. Коуэлл
1007    В. В. Ступкин
1008   М. А. Тынкевич
1009       Д. Б. Фукс

[1010 rows x 1 columns]

Найдите всех авторов с инициалами "С. А.". Автор в базе определяется так: И. О. Фамилия

In [201]:
q_authors_CA = """
SELECT 
    name
  FROM 
    author
  WHERE 
    name 
   LIKE 
    ('С. А.%');
"""

pd.read_sql(q_authors_CA, con)

                name
0      С. А. Айвазян
1   С. А. Орловского
2       С. А. Смоляк
3     С. А. Айвазян
4     С. А. Калмыков
5   С. А. Дубровский
6      С. А. Аристов
7      С. А. Иванков
8     С. А. Айвазяна
9    С. А. Горбатков
10   С. А. Орловский
11     С. А. Ашманов
12       С. А. Орлов

Найдите все издательства, название которых состоит из двух и более слов.

In [202]:
q_publisher_2w = """
SELECT 
    name
  FROM 
    publisher
  WHERE 
    name 
   LIKE 
    '% %';
"""

pd.read_sql(q_publisher_2w, con)

                   name
0          Новое знание
1   Экономическая школа
2             Высш. шк.
3         Радио и связь
4    Гyманитарный Центр
..                  ...
58             ИПП Куна
59            ДМК Пресс
60         Новое звание
61              ИПУ РАН
62   Новосиб. гос. ун-т

[63 rows x 1 columns]

Выведите список книг, выпущенных в издательстве "Мир".

In [203]:
q_publisher_mir = """
SELECT 
    publisher.name,
    book.title
  FROM 
    publisher,
    book 
  WHERE 
      book.publisher_id = publisher.id 
    AND 
      publisher.name = 'Мир';
"""

pd.read_sql(q_publisher_mir, con)

   name                                              title
0   Мир  Имитационное моделирование систем: искусство и...
1   Мир  Введение в имитационное моделирование и язык С...
2   Мир                       Основы исследования операций
3   Мир      Выпуклые структуры и математическая экономика
4   Мир    Нелинейное программирование. Теория и алгоритмы
..  ...                                                ...
79  Мир                   Линейная алгебра и ее применение
80  Мир  Теория синтаксического анализа, перевода и ком...
81  Мир  Теория синтаксического анализа, перевода и ком...
82  Мир       Введение в программирование на языке Паскаль
83  Мир                  Программирование на языке Паскаль

[84 rows x 2 columns]

Выведите количество книг, принадлежащих каждой из категорий. Результат отсортировать по возрастанию.

In [204]:
q_categ_dist = """
SELECT DISTINCT 
      book.category_id
  FROM 
      book;
"""

pd.read_sql(q_categ_dist, con)

   category_id
0            1
1            2
2            3
3            4

In [205]:
q_categ_count = """
SELECT 
       book.category_id AS category,
       COUNT(book.title) AS books
  FROM
       book
  GROUP BY
      book.category_id 
  ORDER BY books ASC;
"""

pd.read_sql(q_categ_count, con)

   category  books
0         2    198
1         1    201
2         4    214
3         3    215

Выведите количество книг, выпущенных в каждом издательстве. В итоговом списке оставьте только те издательства, которые выпустили 3 и более книг. Результат отсортировать по убыванию.

In [206]:
q_categ_count2 = """

SELECT *
FROM (
      SELECT 
            publisher.name AS publisher,
            COUNT(book.title) AS books
        FROM
            publisher,
            book
        WHERE 
            book.publisher_id = publisher.id
        GROUP BY
            publisher 
        ORDER BY books DESC
      )
WHERE 
    books >= 3;
"""

pd.read_sql(q_categ_count2 , con)

                 publisher  books
0                    Наука    152
1                      Мир     84
2     Финансы и статистика     38
3                ФИЗМАТЛИТ     28
4            Радио и связь     26
5               Статистика     26
6                    Питер     23
7                  Вильямс     20
8                Высш. шк.     19
9           Машиностроение     15
10              ЮНИТИ-ДАНА     15
11                 ИНФРА-М     12
12              Сов. радио     12
13                Прогресс      9
14               Экономика      9
15           БХВ-Петербург      8
16                    Дело      7
17                  Знание      7
18                     ИИЛ      7
19                     МГУ      6
20                    МЭСИ      6
21          Едиториал УРСС      5
22             Просвещение      5
23     Экономическая школа      5
24         Энергоатомиздат      5
25              Юнити-Дана      5
26                     ВГУ      4
27                     ЛКИ      4
28                     НГУ      4
29             Наук. думка      4
30               Физматлит      4
31                 Экзамен      4
32                   Эксмо      4
33                 Энергия      4
34                     АНХ      3
35                Академия      3
36                  ГУ ВШЭ      3
37           Дело и Сервис      3
38                ЛИБРОКОМ      3
39                      ЛУ      3
40             Символ-Плюс      3
41  Советская Энциклопедия      3
42               Физматгиз      3
43                 Штиинца      3

Выведите список книг, автором которых являлся <<С. А. Айвазян>>.

In [207]:
q_vasyan = """
SELECT 
    name,
    title
  FROM
    authorbook
  INNER JOIN 
    book
  ON authorbook.book_id = book.id 
  INNER JOIN 
    author
  ON authorbook.author_id = author.id
  WHERE 
    name = 'С. А. Айвазян';
"""

pd.read_sql(q_vasyan, con)

            name                                              title
0  С. А. Айвазян                              Социальные индикаторы
1  С. А. Айвазян  Прикладная статистика. Основы эконометрики: Уч...
2  С. А. Айвазян  Прикладная статистика: Классификации и снижени...
3  С. А. Айвазян   Прикладная статистика: Исследование зависимостей
4  С. А. Айвазян  Прикладная статистика: Основы моделирования и ...
5  С. А. Айвазян                 Статистика. Вероятность. Экономика
6  С. А. Айвазян               Классификация многомерных наблюдений
7  С. А. Айвазян      Прикладная статистика в задачах и упражнениях

В каких издательствах и сколько выпускались книги за авторством <<С. А. Айвазян>>. Результат отсортировать по убыванию.

In [208]:
q_vasyan_caunter = """
SELECT
  author.name,
  publisher.name AS publisher,
  COUNT(book.title) AS count
FROM
  author
INNER JOIN
  authorbook
ON author.id = author_id
INNER JOIN
  book
ON book_id = book.id
INNER JOIN
  publisher
ON publisher_id = publisher.id
WHERE
  author.name = 'С. А. Айвазян'
GROUP BY
  publisher
ORDER BY count DESC
"""

pd.read_sql(q_vasyan_caunter, con)

            name             publisher  count
0  С. А. Айвазян  Финансы и статистика      3
1  С. А. Айвазян            ЮНИТИ-ДАНА      2
2  С. А. Айвазян                 Наука      1
3  С. А. Айвазян            Статистика      1
4  С. А. Айвазян            Юнити-Дана      1

In [209]:
con.close()